language: node_js
node_js: stable

distï¼šTrusty

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - hexo g

after_script:
  - cd public
  - git init
  - git config user.name "zpf124"
  - git config user.email "zpf-fly@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master


branches:
  only:
    - origin
env:
 global:
   - GH_REF: github.com/zpf124/zpf124.github.io.git